### PR TITLE
Fixed the output of reporting classes

### LINKED ISSUE #307: Sarif Reporter prints wrong version number
Class `SARIFHelper` currently has hardcoded version details about the current version of CryptoAnalysis. 

We need to change this, so it always reports the correct, current version of the tool.

### PR DESCRIPTION
**Pull request by svenfeld**
fixes #307 
This pull requests fixes the reporting format of the sarifoutput. 
Also fixes the output for txt and csv.

### CODE REVIEW

File: CryptoAnalysis/src/main/java/crypto/reporting/CSVReporter.java [hunk 1]
```diff
@@ -190,6 +190,8 @@ private void writeToFile() {
 				line.add(string);
 			}
 			writer.write(Joiner.on(CSV_SEPARATOR).join(line) + "\n");
+			writer.write("\n"+REPORT_NAME.substring(0,14)+"\n");
```
Comment (AnakinSklavenwalker) [inline CryptoAnalysis/src/main/java/crypto/reporting/CSVReporter.java:193]: 14 looks very concrete to me. Is is save to use?

**Review by AnakinSklavenwalker — COMMENTED** [review]
Hey @svenfeld can you confirm the changes work on the compiled binary?

File: CryptoAnalysis/src/main/java/crypto/reporting/CSVReporter.java (hunk 1 above)
Comment (svenfeld) [reply CryptoAnalysis/src/main/java/crypto/reporting/CSVReporter.java]: I changed this and also how the version is loaded.

**Review by enriozuni — APPROVED** [review]

File: CryptoAnalysis/src/main/java/crypto/reporting/ReporterHelper.java [hunk 2]
```diff
@@ -69,13 +69,13 @@ public static String generateReport(List<CrySLRule> rules, Collection<IAnalysisS
 			}
 			report += "\n";
 		}
-		report += "======================= CogniCrypt Summary ==========================\n";
+		report += "======================= CryptoAnalysis Summary ==========================\n";
 		report += String.format("\tNumber of CrySL rules: %s\n", rules.size());
```
Comment (aimiebell) [inline CryptoAnalysis/src/main/java/crypto/reporting/ReporterHelper.java:73]: I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [FS: Format string should use %n rather than n (VA_FORMAT_STRING_USES_NEWLINE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#fs-format-string-should-use-n-rather-than-n-va-format-string-uses-newline).
This format string includes a newline character (\n). In format strings, it is generally  preferable to use %n, which will produce the platform-specific line separator.

**Review by AnakinSklavenwalker — APPROVED** [review]
